=== AshishSharma4997/EmployeeCIA/EMPLOYEE.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Ashu_Sharma">
		<xsd:complexType>
		
		<xsd:element name="Members">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="Id" type="xs:integer"/>
					<xsd:element name="Name" type="xs:string"/>
					<xsd:element name="Age" type="xs:string"/>
					<xsd:element name="Salary" type="xs:integer">
					
 
    <xsd:restriction base="xs:integer">
      <xsd:minInclusive value="50000"/>
      <xsd:maxInclusive value="200000"/>
    </xsd:restriction>

</xsd:element>
					<xsd:element name="Email_ID" type="xs:string"/>
					<xsd:element name="Mobile" type="xs:integer"/>
					<xsd:element name="Designation" type="xs:string"/>
						<xsd:element name="Promotion" type="xs:string"/>
				
				
					
				
					
					
				</xsd:sequence>	
			</xsd:complexType>
		</xsd:element>

	</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== AshishSharma4997/EmployeeCIA/EMPLOYEE.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EMPLOYEE.xsl"?>
<Ashu_Sharma xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="EMPLOYEE.xsd">
	
	<Members>
		<Id>1</Id>
		<Name>Ashish</Name>
		<Age>55</Age>
		<Salary>55000</Salary>
		<Email_ID>ashish.sharma@mca.christuniversity.in</Email_ID>
		<Mobile>7976532237</Mobile>
		<Designation>Developer</Designation>	
				<Promotion>Developer</Promotion>		
	</Members>
	
	<Members>
			<Id>2</Id>
		<Name>Ayush</Name>
		<Age>49</Age>
		<Salary>62000</Salary>
		<Email_ID>as.ukg@gmail.com</Email_ID>
		<Mobile>9872339129</Mobile>
		<Designation>Web Designer</Designation>	
		<Promotion>Developer</Promotion>
	</Members>
	
	<Members>
			<Id>3</Id>
		<Name>Neeraj</Name>
		<Age>45</Age>
		<Salary>52000</Salary>
		<Email_ID>neeraj@gmail.com</Email_ID>
		<Mobile>7743423401</Mobile>
		<Designation>Android Developer</Designation>	
		<Promotion>Developer</Promotion>
	</Members>
	
	<Members>
		<Id>4</Id>
		<Name>Sandeep</Name>
		<Age>35</Age>
		<Salary>150000</Salary>
		<Email_ID>Sandeep@gmail.com</Email_ID>
		<Mobile>7891492341</Mobile>
		<Designation>React JS Developer</Designation>	
		<Promotion>Developer</Promotion>
	</Members>


	
</Ashu_Sharma>
